config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'

  resources :songs

  resources :users do
    resources :songs
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs

  def self.find_or_create(name)
    find_by_normalized_name(normalize(name)) || create(:name => name)
  end

  def name=(new_name)
    self[:name]            = new_name
    self[:normalized_name] = normalized_name
  end

  def normalized_name
    self.class.normalize(name)
  end

  def normalized_name=
    raise "Just set the name dude"
  end

  private

  def self.normalize(name_string)
    name_string.gsub(/[^a-zA-Z0-9 ]/,"").downcase
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  belongs_to :user

  validates :user, presence: true

  def name=(new_name)
    self[:name]            = new_name
    self[:normalized_name] = normalize(name)
  end

  def normalized_name=
    raise "Just set the name dude"
  end

  private

  def normalize(name_string)
    name_string.gsub(/[^a-zA-Z0-9 ]/,"").downcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :songs

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    if current_user.nil?
      render :nothing => true, :status => :unauthorized
    end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :ensure_logged_in
  skip_before_action :ensure_logged_in, only: [:index, :show]

  # Show all songs (optionally those owned by a particular user)
  def index
    if params[:user_id]
      @owner = User.find(params[:user_id])
      @songs = Song.where(:user => @owner)
    else
      @songs = Song.all
    end
  end

  def show
    @song = Song.find(params[:id])

    # Handle 404
  end

  # Start creating a new song
  def new
    @song = Song.new

    render "edit"
  end

  # Add a song
  def create
    @song = Song.new(song_params.merge(:user => current_user))
    @song.artist = Artist.find_or_create(params.permit(:artist)[:artist])
    @song.save

    # Add flash notice

    redirect_to @song

    # Rescue errors
  end

  # Start editing an existing song
  def edit
    @song = Song.where(:user => current_user).find(params[:id])
    # Handle 404
  end

  # Update a song
  def update
    @song = Song.where(:user => current_user).find(params[:id])
    @song.update_attributes(song_params)

    # Add flash notice

    redirect_to @song

    # Rescue errors
  end

  # Delete a song
  def delete
    @song = Song.where(:user => current_user).find(params[:id])
    @song.destroy

    # Add flash notice
    redirect_to songs_path

    # Rescue errors
  end

  private

  def song_params
    params[:song].permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getdown</title>
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'blueprint/screen.css', media: 'screen, projection' %>
  <%= stylesheet_link_tag    'blueprint/print.css',  media: 'print' %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag  'blueprint/ie.css', media: 'screen, projection' %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="site-header">
  <div class="container">
    <div class="span-24 header">

      <a href="/" class="home-link"><%= image_tag 'getdown-logo.svg', width: '160', class: 'site-logo' %></a>

      <p class="tagline">Visualize <span class="note note1">♫</span> Play <span class="note note2">♫</span> Get Down</p>

      <div id="user_nav" class="user-nav">
        <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="span-24">
    <%= yield %>
  </div>

  <div class="span-24 footer">
    <p>We hope you like jamming too.</p>
  </div>
</div>

</body>
</html>

app/views/songs/_song.html.erb
<tr class="song">
  <td class="user"><%= link_to song.user.name, user_songs_url(song.user) %></td>
  <td class="artist"><%= song.artist.name %></td>
  <td class="title"><%= link_to song.name, song %></td>
</tr>

app/views/songs/edit.html.erb
<h2>Add this song</h2>

<%= form_for @song do |f| %>
  <%= label_tag :artist %><%= text_field_tag :artist, @song.artist.try(:name) %>
  <%= f.label :name %><%= f.text_field :name %>
  <%= f.label :body %><%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<% if @songs.empty? %>
  Erm, plz to be adding something
<% else %>
  <% if @owner
       whose = @owner == current_user ? "your" : "#{@owner.name}'s"
     else
       whose = "the"
     end %>

  <h2>These are all <%= whose %> songs</h2>
  <% if current_user %>
    <div class="add-song"><%= link_to "Add a song", new_song_path %></div>
  <% end %>

  <table>
    <tr><th>Added by</th><th>Artist</th><th>Song</th></tr>
    <%= render partial: "song", collection: @songs %>
  </table>
<% end %>

app/views/songs/show.html.erb
<h2><%= @song.artist.name %>: <%= @song.name %></h2>

<table class="song">
  <%= Chordpro.colorized(@song.body, :show_title => false).html_safe %>
</table>